from __future__ import annotations

import argparse
import re
import sqlite3
import tempfile
from pathlib import Path

from app.db import Database


OMITTED_TABLES = {"memory_fts", "schema_migrations", "sqlite_sequence"}


def _table_sql(sql: str) -> str:
    sql = re.sub(
        r"INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        sql,
        flags=re.IGNORECASE,
    )
    sql = re.sub(r"\bCREATE TABLE\b", "CREATE TABLE IF NOT EXISTS", sql, count=1)
    sql = re.sub(
        r"\s+REFERENCES\s+[A-Za-z_][A-Za-z0-9_]*\s*\([^)]*\)"
        r"(?:\s+ON\s+DELETE\s+(?:CASCADE|SET\s+NULL|RESTRICT|NO\s+ACTION))?",
        "",
        sql,
        flags=re.IGNORECASE,
    )
    return sql.rstrip(";") + ";"


def generate() -> str:
    with tempfile.TemporaryDirectory(
        prefix="better-agent-schema-", ignore_cleanup_errors=True
    ) as directory:
        path = Path(directory) / "source.db"
        Database(path)
        with sqlite3.connect(path) as connection:
            rows = connection.execute(
                "SELECT type,name,tbl_name,sql FROM sqlite_master "
                "WHERE sql IS NOT NULL AND type IN ('table','index') "
                "ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END,rowid"
            ).fetchall()
            tables = [row[1] for row in rows if row[0] == "table"]
            foreign_keys = {
                table: connection.execute(f'PRAGMA foreign_key_list("{table}")').fetchall()
                for table in tables
                if table not in OMITTED_TABLES and not table.startswith("memory_fts_")
            }

    statements: list[str] = []
    for kind, name, table, sql in rows:
        if (
            table in OMITTED_TABLES
            or table.startswith("memory_fts_")
            or name.startswith("sqlite_autoindex")
        ):
            continue
        if kind == "table":
            statements.append(_table_sql(sql))
        elif "CREATE INDEX" in sql or "CREATE UNIQUE INDEX" in sql:
            statements.append(sql.rstrip(";") + ";")
    for table, keys in foreign_keys.items():
        for key_id, seq, target, source_column, target_column, _update, on_delete, _match in keys:
            if seq != 0:
                raise RuntimeError(f"composite foreign key requires manual migration: {table}:{key_id}")
            suffix = f" ON DELETE {on_delete}" if on_delete and on_delete != "NO ACTION" else ""
            statements.append(
                f'ALTER TABLE "{table}" ADD CONSTRAINT "fk_{table}_{source_column}_{key_id}" '
                f'FOREIGN KEY ("{source_column}") REFERENCES "{target}" ("{target_column}"){suffix};'
            )
    return "\n\n".join(statements) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.write_text(generate(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
