CREATE TABLE IF NOT EXISTS goals (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    project_id TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    goal_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS runs (
    id TEXT PRIMARY KEY,
    goal_id TEXT NOT NULL,
    session_id TEXT,
    state TEXT NOT NULL,
    resume_state TEXT,
    current_plan_version_id TEXT,
    current_step_id TEXT,
    checkpoint_id TEXT,
    version INTEGER NOT NULL DEFAULT 0,
    budget_json TEXT NOT NULL DEFAULT '{}',
    skill_names_json TEXT NOT NULL DEFAULT '[]',
    source_turn_id TEXT,
    source_plan_document_id TEXT,
    source_plan_document_version_id TEXT,
    source_plan_content_hash TEXT,
    error_json TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
, runtime_bundle_id TEXT);

CREATE TABLE IF NOT EXISTS threads (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    active_turn_id TEXT,
    next_event_seq INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT
, owner_id TEXT NOT NULL DEFAULT 'local-user', project_id TEXT);

CREATE TABLE IF NOT EXISTS turns (
    id TEXT PRIMARY KEY,
    thread_id TEXT NOT NULL,
    client_turn_id TEXT NOT NULL,
    parent_turn_id TEXT,
    status TEXT NOT NULL,
    policy TEXT,
    content_shape TEXT,
    reason_code TEXT,
    version INTEGER NOT NULL DEFAULT 0,
    skill_names_json TEXT NOT NULL DEFAULT '[]',
    artifact_kind TEXT,
    artifact_operation TEXT,
    artifact_title TEXT,
    plan_context_document_id TEXT,
    plan_context_version_id TEXT,
    plan_context_version INTEGER,
    plan_context_hash TEXT,
    materialized_goal_id TEXT,
    materialized_run_id TEXT,
    direction_action TEXT,
    direction_idempotency_key TEXT UNIQUE,
    direction_projection_status TEXT,
    direction_projection_source_document_id TEXT,
    direction_projection_source_version_id TEXT,
    direction_projection_source_hash TEXT,
    direction_projection_draft_json TEXT,
    direction_projection_error TEXT,
    direction_projection_claim_owner TEXT,
    direction_projection_lease_until TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL, runtime_bundle_id TEXT, goal_action_id TEXT,
    UNIQUE(thread_id, client_turn_id)
);

CREATE TABLE IF NOT EXISTS turn_asks (
    id TEXT PRIMARY KEY,
    turn_id TEXT NOT NULL,
    call_id TEXT NOT NULL UNIQUE,
    questions_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    answer_json TEXT,
    answer_idempotency_key TEXT UNIQUE,
    continuation_turn_id TEXT,
    created_at TEXT NOT NULL,
    answered_at TEXT,
    cancelled_at TEXT
);

CREATE TABLE IF NOT EXISTS turn_jobs (
    turn_id TEXT PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'QUEUED',
    lease_owner TEXT,
    lease_until TEXT,
    attempts INTEGER NOT NULL DEFAULT 0,
    cancel_requested_at TEXT,
    started_at TEXT,
    finished_at TEXT,
    last_error_json TEXT
);

CREATE TABLE IF NOT EXISTS thread_messages (
    id TEXT PRIMARY KEY,
    thread_id TEXT NOT NULL,
    turn_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    status TEXT NOT NULL,
    generation INTEGER NOT NULL DEFAULT 1,
    content_length INTEGER NOT NULL DEFAULT 0,
    plan_document_version_id TEXT,
    created_at TEXT NOT NULL,
    completed_at TEXT
, message_seq INTEGER, presentation TEXT NOT NULL DEFAULT 'standard', research_job_id TEXT);

CREATE TABLE IF NOT EXISTS thread_events (
    row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_version INTEGER NOT NULL,
    event_id TEXT NOT NULL UNIQUE,
    seq INTEGER NOT NULL,
    thread_id TEXT NOT NULL,
    turn_id TEXT NOT NULL,
    type TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    actor TEXT NOT NULL,
    data_json TEXT NOT NULL,
    UNIQUE(thread_id, seq)
);

CREATE TABLE IF NOT EXISTS interactions (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS plan_versions (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    goal_id TEXT NOT NULL DEFAULT '',
    version INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    summary TEXT NOT NULL DEFAULT '',
    base_version INTEGER,
    source_document_version_id TEXT,
    created_at TEXT NOT NULL,
    approved_at TEXT,
    UNIQUE(run_id, version)
);

CREATE TABLE IF NOT EXISTS plan_steps (
    row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id TEXT NOT NULL,
    plan_version_id TEXT NOT NULL,
    position INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'pending',
    atomic INTEGER NOT NULL DEFAULT 1,
    completed_at TEXT,
    canceled_at TEXT,
    UNIQUE(plan_version_id, position),
    UNIQUE(plan_version_id, id)
);

CREATE TABLE IF NOT EXISTS plan_documents (
    id TEXT PRIMARY KEY,
    thread_id TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    current_version_id TEXT,
    projected_version_id TEXT,
    file_status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT
);

CREATE TABLE IF NOT EXISTS plan_document_versions (
    id TEXT PRIMARY KEY,
    plan_document_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    base_version_id TEXT,
    title TEXT NOT NULL,
    markdown_content TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    source_turn_id TEXT,
    source_message_id TEXT,
    actor TEXT NOT NULL,
    change_summary TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    committed_at TEXT,
    UNIQUE(plan_document_id, version),
    UNIQUE(source_turn_id),
    UNIQUE(source_message_id)
);

CREATE TABLE IF NOT EXISTS plan_write_intents (
    id TEXT PRIMARY KEY,
    plan_document_id TEXT NOT NULL,
    version_id TEXT NOT NULL UNIQUE,
    expected_head_version_id TEXT,
    expected_file_hash TEXT,
    target_file_hash TEXT NOT NULL,
    status TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error_json TEXT,
    created_at TEXT NOT NULL,
    finished_at TEXT
);

CREATE TABLE IF NOT EXISTS checkpoints (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    state TEXT NOT NULL,
    plan_version_id TEXT,
    step_id TEXT,
    payload_json TEXT NOT NULL,
    last_event_seq INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    interaction_id TEXT,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_version INTEGER NOT NULL,
    event_id TEXT NOT NULL UNIQUE,
    seq INTEGER NOT NULL,
    run_id TEXT NOT NULL,
    goal_id TEXT NOT NULL,
    type TEXT NOT NULL,
    occurred_at TEXT NOT NULL,
    actor TEXT NOT NULL,
    correlation_json TEXT NOT NULL,
    data_json TEXT NOT NULL,
    UNIQUE(run_id, seq)
);

CREATE TABLE IF NOT EXISTS approvals (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    tool_call_id TEXT NOT NULL,
    params_hash TEXT NOT NULL,
    params_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL,
    acted_at TEXT,
    expires_at TEXT, binding_json TEXT NOT NULL DEFAULT '{}', binding_digest TEXT NOT NULL DEFAULT '',
    UNIQUE(run_id, tool_call_id, params_hash)
);

CREATE TABLE IF NOT EXISTS memory_candidates (
    id TEXT PRIMARY KEY,
    run_id TEXT,
    kind TEXT NOT NULL,
    content TEXT NOT NULL,
    scope TEXT NOT NULL,
    project_id TEXT,
    skill_name TEXT,
    confidence REAL NOT NULL,
    evidence_event_ids_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'proposed',
    memory_version INTEGER,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS memory_file_versions (
    id TEXT PRIMARY KEY,
    path TEXT NOT NULL,
    version INTEGER NOT NULL,
    content_hash TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE(path, version)
);

CREATE TABLE IF NOT EXISTS run_stats (
    run_id TEXT PRIMARY KEY,
    projection_version INTEGER NOT NULL DEFAULT 1,
    stats_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tool_calls (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    tool_name TEXT NOT NULL,
    params_hash TEXT NOT NULL,
    risk TEXT NOT NULL,
    status TEXT NOT NULL,
    result_json TEXT,
    created_at TEXT NOT NULL,
    completed_at TEXT
);

CREATE TABLE IF NOT EXISTS memory_entries (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL,
 kind TEXT NOT NULL CHECK(kind IN ('preference','constraint','fact','decision','lesson')),
 scope_type TEXT NOT NULL CHECK(scope_type IN ('user','project')), scope_id TEXT NOT NULL DEFAULT '',
 status TEXT NOT NULL CHECK(status IN ('ACTIVE','ARCHIVED','PURGED')), current_revision_id TEXT,
 canonical_fingerprint TEXT NOT NULL, pinned INTEGER NOT NULL DEFAULT 0 CHECK(pinned IN (0,1)),
 importance REAL NOT NULL DEFAULT .5 CHECK(importance BETWEEN 0 AND 1), sensitivity TEXT NOT NULL DEFAULT 'normal',
 valid_until TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
, evidence_state TEXT NOT NULL DEFAULT 'LEGACY_UNVERIFIED' CHECK(evidence_state IN ('VERIFIED','LEGACY_UNVERIFIED','INVALID')));

CREATE TABLE IF NOT EXISTS memory_revisions (
 id TEXT PRIMARY KEY, entry_id TEXT NOT NULL,
 revision_no INTEGER NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('CREATE','UPDATE','ROLLBACK','RESTORE')),
 content TEXT NOT NULL, content_hash TEXT NOT NULL, base_revision_id TEXT, actor TEXT NOT NULL,
 source_refs_json TEXT NOT NULL DEFAULT '[]', reason TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL,
 UNIQUE(entry_id,revision_no)
);

CREATE TABLE IF NOT EXISTS conversation_archive_state (
 owner_id TEXT NOT NULL, thread_id TEXT NOT NULL,
 archived_through_seq INTEGER NOT NULL DEFAULT 0, reserved_start_seq INTEGER, reserved_end_seq INTEGER, source_hash TEXT,
 state TEXT NOT NULL DEFAULT 'IDLE' CHECK(state IN ('IDLE','RESERVED','FAILED')), lease_owner TEXT, lease_until TEXT,
 attempts INTEGER NOT NULL DEFAULT 0, error TEXT, lease_epoch INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(owner_id,thread_id)
);

CREATE TABLE IF NOT EXISTS memory_episodes (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, thread_id TEXT NOT NULL, project_id TEXT,
 start_message_seq INTEGER NOT NULL, end_message_seq INTEGER NOT NULL, source_hash TEXT NOT NULL, summary TEXT NOT NULL,
 topics_json TEXT NOT NULL DEFAULT '[]', decisions_json TEXT NOT NULL DEFAULT '[]', open_loops_json TEXT NOT NULL DEFAULT '[]',
 sensitivity TEXT NOT NULL DEFAULT 'normal', retrieval_policy TEXT NOT NULL DEFAULT 'thread', retain_until TEXT,
 status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','ARCHIVED','DELETED','RAW_REFERENCE')),
 supersedes_episode_id TEXT, model_id TEXT, prompt_version TEXT NOT NULL DEFAULT 'episode-v1', created_at TEXT NOT NULL, schema_version TEXT NOT NULL DEFAULT 'episode-v1', synopsis_json TEXT NOT NULL DEFAULT '[]', outcomes_json TEXT NOT NULL DEFAULT '[]', source_message_ids_json TEXT NOT NULL DEFAULT '[]', source_token_count INTEGER NOT NULL DEFAULT 0, summary_token_count INTEGER NOT NULL DEFAULT 0, tokenizer_version TEXT NOT NULL DEFAULT 'utf8-upper-bound-v1', deleted_at TEXT, version INTEGER NOT NULL DEFAULT 0,
 UNIQUE(owner_id,thread_id,start_message_seq,end_message_seq,source_hash)
);

CREATE TABLE IF NOT EXISTS memory_context_pins (
 model_invocation_id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, parent_type TEXT NOT NULL, parent_id TEXT NOT NULL, purpose TEXT NOT NULL,
 query_hash TEXT NOT NULL, scope_hash TEXT NOT NULL, revision_ids_json TEXT NOT NULL, episode_ids_json TEXT NOT NULL,
 tokenizer_version TEXT NOT NULL, renderer_version TEXT NOT NULL, budget_json TEXT NOT NULL, token_count INTEGER NOT NULL,
 rendered_hash TEXT NOT NULL, invocation_state TEXT NOT NULL DEFAULT 'PREPARED', invalidated_at TEXT, created_at TEXT NOT NULL
, binding_hash TEXT NOT NULL DEFAULT '', expires_at TEXT, invalidation_reason TEXT);

CREATE TABLE IF NOT EXISTS memory_projection_intents (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, path TEXT NOT NULL, expected_hash TEXT, target_hash TEXT NOT NULL,
 state TEXT NOT NULL CHECK(state IN ('PENDING','COMMITTED','FAILED','CONFLICT')), attempts INTEGER NOT NULL DEFAULT 0,
 error TEXT, created_at TEXT NOT NULL, finished_at TEXT
);

CREATE TABLE IF NOT EXISTS legacy_memory_mappings (legacy_id TEXT PRIMARY KEY, disposition TEXT NOT NULL, target_id TEXT, reason TEXT NOT NULL DEFAULT '');

CREATE TABLE IF NOT EXISTS research_jobs (
 id TEXT PRIMARY KEY, thread_id TEXT NOT NULL, source_turn_id TEXT NOT NULL UNIQUE,
 schedule_id TEXT, retry_of_job_id TEXT,
 trigger_kind TEXT NOT NULL CHECK(trigger_kind IN ('manual','scheduled','retry','run_now')), occurrence_key TEXT NOT NULL UNIQUE,
 topic TEXT NOT NULL CHECK(length(topic) BETWEEN 1 AND 2000), source_scopes_json TEXT NOT NULL DEFAULT '["web"]',
 status TEXT NOT NULL CHECK(status IN ('QUEUED','RUNNING','COMPLETED','PARTIAL','FAILED','CANCELLED')),
 phase TEXT NOT NULL CHECK(phase IN ('queued','planning','retrieving','distilling','reflecting','curating','writing','summarizing','finalizing','completed','partial','failed','cancelled')),
 available_at TEXT NOT NULL, lease_owner TEXT, lease_until TEXT, attempts INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL DEFAULT 2,
 cancel_requested_at TEXT, started_at TEXT, finished_at TEXT, last_error_json TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS research_job_attempts (
 id TEXT PRIMARY KEY, job_id TEXT NOT NULL, attempt INTEGER NOT NULL,
 lease_owner TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('RUNNING','COMPLETED','FAILED','LEASE_LOST','CANCELLED')),
 started_at TEXT NOT NULL, finished_at TEXT, error_json TEXT, UNIQUE(job_id,attempt)
);

CREATE TABLE IF NOT EXISTS research_reports (
 job_id TEXT PRIMARY KEY, title TEXT, outline_json TEXT, summary_json TEXT, markdown TEXT,
 partial_markdown TEXT NOT NULL DEFAULT '', source_count INTEGER NOT NULL DEFAULT 0, evidence_count INTEGER NOT NULL DEFAULT 0,
 assistant_message_id TEXT UNIQUE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, completed_at TEXT
);

CREATE TABLE IF NOT EXISTS research_sources (
 id TEXT PRIMARY KEY, job_id TEXT NOT NULL, ordinal INTEGER NOT NULL,
 kind TEXT NOT NULL CHECK(kind IN ('web','local_note')), canonical_url TEXT, locator TEXT, title TEXT NOT NULL, content TEXT NOT NULL,
 content_hash TEXT NOT NULL, published_at TEXT, retrieved_at TEXT NOT NULL, quality_score REAL NOT NULL, metadata_json TEXT NOT NULL DEFAULT '{}',
 UNIQUE(job_id,ordinal), UNIQUE(job_id,kind,content_hash)
);

CREATE TABLE IF NOT EXISTS research_evidence (
 id TEXT PRIMARY KEY, job_id TEXT NOT NULL,
 source_id TEXT NOT NULL, text TEXT NOT NULL, date_hint TEXT,
 relevance REAL NOT NULL CHECK(relevance BETWEEN 0 AND 1), created_at TEXT NOT NULL, UNIQUE(job_id,source_id,text)
);

CREATE TABLE IF NOT EXISTS research_sections (
 id TEXT PRIMARY KEY, job_id TEXT NOT NULL, ordinal INTEGER NOT NULL, heading TEXT NOT NULL,
 thesis TEXT NOT NULL DEFAULT '', evidence_ids_json TEXT NOT NULL DEFAULT '[]',
 status TEXT NOT NULL CHECK(status IN ('PENDING','WRITING','COMPLETED')), markdown TEXT NOT NULL DEFAULT '', summary TEXT NOT NULL DEFAULT '',
 generation INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL, completed_at TEXT, UNIQUE(job_id,ordinal)
);

CREATE TABLE IF NOT EXISTS research_schedules (
 id TEXT PRIMARY KEY, name TEXT NOT NULL, thread_id TEXT NOT NULL UNIQUE, topic TEXT NOT NULL,
 source_scopes_json TEXT NOT NULL DEFAULT '["web"]', trigger_type TEXT NOT NULL CHECK(trigger_type IN ('daily','weekly','interval_hours')),
 trigger_time TEXT, trigger_weekday INTEGER CHECK(trigger_weekday BETWEEN 0 AND 6), interval_hours INTEGER CHECK(interval_hours BETWEEN 1 AND 720),
 timezone TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)), notify_enabled INTEGER NOT NULL DEFAULT 1 CHECK(notify_enabled IN (0,1)),
 next_run_at TEXT, last_run_at TEXT, last_job_id TEXT, deleted_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 CHECK((trigger_type='daily' AND trigger_time IS NOT NULL AND trigger_weekday IS NULL AND interval_hours IS NULL)
 OR (trigger_type='weekly' AND trigger_time IS NOT NULL AND trigger_weekday IS NOT NULL AND interval_hours IS NULL)
 OR (trigger_type='interval_hours' AND trigger_time IS NULL AND trigger_weekday IS NULL AND interval_hours IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS notification_channels (
 id TEXT PRIMARY KEY, name TEXT NOT NULL, channel_type TEXT NOT NULL CHECK(channel_type IN ('serverchan','wecom','dingtalk','webhook')),
 secret_env_name TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 UNIQUE(channel_type,name)
);

CREATE TABLE IF NOT EXISTS notification_deliveries (
 id TEXT PRIMARY KEY, job_id TEXT NOT NULL,
 channel_id TEXT NOT NULL, attempt INTEGER NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('PENDING','SENT','FAILED')), http_status INTEGER, provider_code TEXT, error TEXT,
 created_at TEXT NOT NULL, finished_at TEXT, UNIQUE(job_id,channel_id,attempt)
);

CREATE TABLE IF NOT EXISTS app_settings (
 id INTEGER PRIMARY KEY CHECK(id=1), human_mode INTEGER NOT NULL DEFAULT 0 CHECK(human_mode IN (0,1)), updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS goal_programs (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL,
 source_thread_id TEXT NOT NULL,
 source_plan_document_id TEXT NOT NULL,
 source_plan_document_version_id TEXT NOT NULL,
 source_plan_content_hash TEXT NOT NULL,
 objective_title TEXT NOT NULL DEFAULT '', objective_summary TEXT NOT NULL DEFAULT '',
 status TEXT NOT NULL CHECK(status IN ('DRAFT','ACTIVE','PAUSED','COMPLETED','CANCELLED')),
 compile_status TEXT NOT NULL CHECK(compile_status IN ('COMPILING','READY','FAILED')),
 compile_error_code TEXT, timezone TEXT NOT NULL, start_date TEXT NOT NULL, end_date TEXT NOT NULL,
 daily_minutes INTEGER NOT NULL CHECK(daily_minutes BETWEEN 5 AND 1440),
 current_program_version_id TEXT, version INTEGER NOT NULL DEFAULT 0,
 next_event_seq INTEGER NOT NULL DEFAULT 1,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, completed_at TEXT, cancelled_at TEXT, deleted_at TEXT
, completion_summary TEXT, completion_episode_id TEXT);

CREATE TABLE IF NOT EXISTS goal_program_versions (
 id TEXT PRIMARY KEY, program_id TEXT NOT NULL, version INTEGER NOT NULL,
 base_version_id TEXT,
 source_plan_document_version_id TEXT NOT NULL,
 structure_json TEXT NOT NULL, change_summary TEXT NOT NULL DEFAULT '', actor TEXT NOT NULL, created_at TEXT NOT NULL,
 UNIQUE(program_id,version)
);

CREATE TABLE IF NOT EXISTS goal_actions (
 id TEXT PRIMARY KEY, program_id TEXT NOT NULL,
 program_version_id TEXT NOT NULL, logical_key TEXT NOT NULL,
 scheduled_date TEXT NOT NULL, position INTEGER NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '',
 estimated_minutes INTEGER NOT NULL CHECK(estimated_minutes BETWEEN 5 AND 180), completion_criteria TEXT NOT NULL,
 required INTEGER NOT NULL CHECK(required IN (0,1)),
 status TEXT NOT NULL CHECK(status IN ('SCHEDULED','COMPLETED','SKIPPED','DEFERRED','CANCELLED')),
 version INTEGER NOT NULL DEFAULT 0, completed_at TEXT, skipped_at TEXT, deferred_at TEXT, cancelled_at TEXT,
 deferred_from_action_id TEXT, cancel_reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 UNIQUE(program_id,program_version_id,logical_key), UNIQUE(program_id,program_version_id,scheduled_date,position)
);

CREATE TABLE IF NOT EXISTS goal_action_feedback (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, action_id TEXT NOT NULL, kind TEXT NOT NULL,
 actual_minutes INTEGER, difficulty INTEGER, reason_code TEXT, note TEXT, sensitivity TEXT NOT NULL DEFAULT 'normal',
 idempotency_key TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(owner_id,idempotency_key)
);

CREATE TABLE IF NOT EXISTS goal_command_receipts (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL,
 operation TEXT NOT NULL, idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL, response_json TEXT NOT NULL,
 created_at TEXT NOT NULL, UNIQUE(owner_id,idempotency_key)
);

CREATE TABLE IF NOT EXISTS goal_program_events (
 row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id TEXT NOT NULL UNIQUE,
 program_id TEXT NOT NULL, seq INTEGER NOT NULL, action_id TEXT,
 type TEXT NOT NULL, actor TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1,
 occurred_at TEXT NOT NULL, data_json TEXT NOT NULL DEFAULT '{}', UNIQUE(program_id,seq)
);

CREATE TABLE IF NOT EXISTS goal_adjustment_proposals (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, program_id TEXT NOT NULL,
 base_program_version_id TEXT NOT NULL,
 expected_plan_document_version_id TEXT NOT NULL, expected_plan_content_hash TEXT NOT NULL,
 affected_actions_json TEXT NOT NULL, candidate_structure_json TEXT NOT NULL, diff_json TEXT NOT NULL, reason TEXT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('PENDING','ACCEPTED','REJECTED','STALE')), version INTEGER NOT NULL DEFAULT 0,
 accepted_program_version_id TEXT,
 plan_sync_status TEXT, plan_sync_version_id TEXT,
 created_at TEXT NOT NULL, decided_at TEXT, updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS goal_daily_reviews (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, program_id TEXT NOT NULL, local_date TEXT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('QUEUED','RUNNING','COMPLETED','FAILED')), attempts INTEGER NOT NULL DEFAULT 0,
 lease_owner TEXT, lease_until TEXT, source_hash TEXT NOT NULL, signals_json TEXT NOT NULL DEFAULT '[]',
 summary TEXT, encouragement TEXT, needs_adjustment INTEGER, adjustment_reason TEXT,
 proposal_id TEXT, error_code TEXT,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, completed_at TEXT,
 UNIQUE(owner_id,program_id,local_date)
);

CREATE TABLE IF NOT EXISTS goal_review_action_snapshots (
 review_id TEXT NOT NULL,
 action_id TEXT NOT NULL, action_version INTEGER NOT NULL, status TEXT NOT NULL,
 title TEXT NOT NULL, estimated_minutes INTEGER NOT NULL, actual_minutes INTEGER, difficulty INTEGER,
 PRIMARY KEY(review_id,action_id)
);

CREATE TABLE IF NOT EXISTS runtime_bundles (
 id TEXT PRIMARY KEY, bundle_hash TEXT NOT NULL UNIQUE, manifest_json TEXT NOT NULL, created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS runtime_channels (
 name TEXT PRIMARY KEY, bundle_id TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 0,
 updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS runtime_channel_events (
 id TEXT PRIMARY KEY, channel_name TEXT NOT NULL, from_bundle_id TEXT, to_bundle_id TEXT NOT NULL,
 idempotency_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_context_snapshots (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, content_json TEXT NOT NULL, content_hash TEXT NOT NULL,
 runtime_bundle_id TEXT NOT NULL, created_at TEXT NOT NULL,
 UNIQUE(owner_id,content_hash,runtime_bundle_id)
);

CREATE TABLE IF NOT EXISTS agent_runs (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, thread_id TEXT, objective TEXT NOT NULL,
 mode TEXT NOT NULL CHECK(mode IN ('single','expert')), status TEXT NOT NULL CHECK(status IN ('QUEUED','RUNNING','WAITING','SUCCEEDED','FAILED','CANCELLED')),
 context_snapshot_id TEXT NOT NULL, runtime_bundle_id TEXT NOT NULL,
 coordinator_task_id TEXT, next_event_seq INTEGER NOT NULL DEFAULT 1,
 budget_units INTEGER NOT NULL DEFAULT 0 CHECK(budget_units>=0), reserved_budget_units INTEGER NOT NULL DEFAULT 0 CHECK(reserved_budget_units>=0),
 idempotency_key TEXT NOT NULL UNIQUE, version INTEGER NOT NULL DEFAULT 0, cancel_requested_at TEXT,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, finished_at TEXT
);

CREATE TABLE IF NOT EXISTS agent_tasks (
 id TEXT PRIMARY KEY, agent_run_id TEXT NOT NULL,
 root_task_id TEXT NOT NULL, parent_task_id TEXT, child_key TEXT,
 role TEXT NOT NULL, objective TEXT NOT NULL, context_snapshot_id TEXT NOT NULL,
 output_schema TEXT NOT NULL DEFAULT 'artifact.v1', status TEXT NOT NULL CHECK(status IN ('QUEUED','RUNNING','WAITING_CHILDREN','SUCCEEDED','FAILED','CANCELLED')),
 priority INTEGER NOT NULL DEFAULT 0, join_policy TEXT CHECK(join_policy IN ('ALL_SUCCESS','ALL_DONE')), children_closed_at TEXT,
 attempts INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL DEFAULT 2,
 lease_owner TEXT, lease_epoch INTEGER NOT NULL DEFAULT 0, lease_until TEXT, available_at TEXT NOT NULL,
 budget_units INTEGER NOT NULL DEFAULT 0 CHECK(budget_units>=0), result_artifact_id TEXT, error_code TEXT,
 cancel_requested_at TEXT, cancel_reason TEXT, version INTEGER NOT NULL DEFAULT 0,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, finished_at TEXT,
 UNIQUE(parent_task_id,child_key)
);

CREATE TABLE IF NOT EXISTS agent_task_attempts (
 id TEXT PRIMARY KEY, task_id TEXT NOT NULL,
 attempt_no INTEGER NOT NULL, lease_owner TEXT NOT NULL, lease_epoch INTEGER NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('RUNNING','SUCCEEDED','FAILED','LEASE_LOST','CANCELLED')),
 started_at TEXT NOT NULL, heartbeat_at TEXT, finished_at TEXT, error_json TEXT, UNIQUE(task_id,attempt_no)
);

CREATE TABLE IF NOT EXISTS agent_task_checkpoints (
 id TEXT PRIMARY KEY, task_id TEXT NOT NULL,
 attempt_no INTEGER NOT NULL, lease_epoch INTEGER NOT NULL, payload_json TEXT NOT NULL, payload_hash TEXT NOT NULL,
 created_at TEXT NOT NULL, UNIQUE(task_id,attempt_no,payload_hash)
);

CREATE TABLE IF NOT EXISTS agent_artifacts (
 id TEXT PRIMARY KEY, task_id TEXT NOT NULL,
 attempt_no INTEGER NOT NULL, lease_epoch INTEGER NOT NULL, artifact_type TEXT NOT NULL, schema_version INTEGER NOT NULL DEFAULT 1,
 content_json TEXT NOT NULL, source_refs_json TEXT NOT NULL DEFAULT '[]', content_hash TEXT NOT NULL,
 redaction_status TEXT NOT NULL DEFAULT 'safe', created_at TEXT NOT NULL, UNIQUE(task_id,attempt_no,artifact_type)
);

CREATE TABLE IF NOT EXISTS agent_events (
 row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id TEXT NOT NULL UNIQUE,
 agent_run_id TEXT NOT NULL, seq INTEGER NOT NULL,
 task_id TEXT, type TEXT NOT NULL, actor TEXT NOT NULL, data_json TEXT NOT NULL DEFAULT '{}', occurred_at TEXT NOT NULL,
 UNIQUE(agent_run_id,seq)
);

CREATE TABLE IF NOT EXISTS tool_execution_claims (
 logical_action_key TEXT PRIMARY KEY, run_id TEXT NOT NULL, task_id TEXT, agent_id TEXT,
 tool_call_id TEXT NOT NULL, tool_name TEXT NOT NULL, params_hash TEXT NOT NULL, target_hash TEXT,
 skill_digest TEXT, policy_version TEXT,
 status TEXT NOT NULL CHECK(status IN ('RUNNING','COMPLETED','FAILED','RECONCILIATION_REQUIRED')),
 lease_epoch INTEGER NOT NULL DEFAULT 1, result_json TEXT, error_code TEXT,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, completed_at TEXT,
 UNIQUE(run_id,tool_call_id)
);

CREATE TABLE IF NOT EXISTS evolution_experiences (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, task_type TEXT NOT NULL, outcome TEXT NOT NULL,
 lineage_group_hash TEXT NOT NULL, source_content_hash TEXT NOT NULL,
 runtime_bundle_id TEXT NOT NULL,
 dataset_partition TEXT NOT NULL CHECK(dataset_partition IN ('DISCOVERY','DEV','HOLDOUT','SAFETY')),
 request_digest TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, source_kind TEXT NOT NULL DEFAULT 'manual', source_id TEXT NOT NULL DEFAULT '', source_event_id TEXT NOT NULL DEFAULT '', signal_type TEXT NOT NULL DEFAULT 'manual', severity TEXT NOT NULL DEFAULT 'info', evidence_json TEXT NOT NULL DEFAULT '{}', failure_tags_json TEXT NOT NULL DEFAULT '[]', observed_at TEXT NOT NULL DEFAULT '', root_task_id TEXT NOT NULL DEFAULT '', target_role TEXT NOT NULL DEFAULT '', provenance TEXT NOT NULL DEFAULT 'production', source_version TEXT NOT NULL DEFAULT '', source_state TEXT NOT NULL DEFAULT 'ACTIVE', runtime_bundle_known INTEGER NOT NULL DEFAULT 1,
 UNIQUE(owner_id,lineage_group_hash)
);

CREATE TABLE IF NOT EXISTS evolution_candidates (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL,
 candidate_type TEXT NOT NULL CHECK(candidate_type IN ('memory','skill','policy','prompt','code')),
 experience_ids_json TEXT NOT NULL, base_bundle_id TEXT NOT NULL,
 target_bundle_id TEXT NOT NULL, target_bundle_digest TEXT NOT NULL,
 proposed_content_json TEXT NOT NULL, proposed_digest TEXT NOT NULL,
 permission_diff_json TEXT NOT NULL, permission_diff_digest TEXT NOT NULL, reason TEXT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('READY_FOR_EVAL','EVALUATED','APPROVED','CANARY','PROMOTED','REJECTED','ROLLED_BACK')),
 version INTEGER NOT NULL DEFAULT 0, current_evaluation_id TEXT, approval_id TEXT, deployment_id TEXT, contract_json TEXT NOT NULL DEFAULT '{}', release_contract_version TEXT NOT NULL DEFAULT '',
 request_digest TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS evolution_evaluations (
 id TEXT PRIMARY KEY, candidate_id TEXT NOT NULL,
 baseline_bundle_id TEXT NOT NULL, candidate_bundle_id TEXT NOT NULL,
 eval_set_digest TEXT NOT NULL, evaluator_digest TEXT NOT NULL,
 deterministic_pass INTEGER NOT NULL CHECK(deterministic_pass IN (0,1)), checks_json TEXT NOT NULL,
 metrics_json TEXT NOT NULL, report_digest TEXT NOT NULL UNIQUE, status TEXT NOT NULL CHECK(status IN ('COMPLETED')),
 request_digest TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, finished_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS evolution_decisions (
 id TEXT PRIMARY KEY, candidate_id TEXT NOT NULL,
 evaluation_id TEXT, decision TEXT NOT NULL CHECK(decision IN ('APPROVE','REJECT','PROMOTE','ROLLBACK')),
 from_bundle_id TEXT, to_bundle_id TEXT, actor TEXT NOT NULL, reason TEXT NOT NULL DEFAULT '',
 candidate_digest TEXT NOT NULL, evaluation_report_digest TEXT NOT NULL,
 permission_diff_digest TEXT NOT NULL, target_bundle_digest TEXT NOT NULL,
 expires_at TEXT, request_digest TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS canary_deployments (
 id TEXT PRIMARY KEY, candidate_id TEXT NOT NULL,
 approval_id TEXT NOT NULL,
 champion_bundle_id TEXT NOT NULL, challenger_bundle_id TEXT NOT NULL,
 allocation_percent INTEGER NOT NULL CHECK(allocation_percent BETWEEN 1 AND 100), assignment_unit TEXT NOT NULL,
 salt_digest TEXT NOT NULL, gate_policy_version TEXT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('ACTIVE','PROMOTED','ROLLED_BACK','STOPPED')),
 target_role TEXT NOT NULL DEFAULT '', target_purpose TEXT NOT NULL DEFAULT '', budget_microusd INTEGER,
 deadline_at TEXT, release_contract_version TEXT NOT NULL DEFAULT '',
 request_digest TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS evolution_events (
 row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id TEXT NOT NULL UNIQUE,
 candidate_id TEXT, type TEXT NOT NULL, actor TEXT NOT NULL, data_json TEXT NOT NULL DEFAULT '{}',
 idempotency_key TEXT NOT NULL UNIQUE, occurred_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS evolution_observer_offsets (
      stream_kind TEXT NOT NULL, owner_id TEXT NOT NULL, last_row_id INTEGER NOT NULL DEFAULT 0,
      last_success_row_id INTEGER NOT NULL DEFAULT 0, last_error TEXT, last_error_at TEXT,
      updated_at TEXT NOT NULL, PRIMARY KEY(stream_kind,owner_id)
    );

CREATE TABLE IF NOT EXISTS evolution_content_authorizations (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, subject_id TEXT NOT NULL, source_scope_json TEXT NOT NULL,
 purpose TEXT NOT NULL, expires_at TEXT NOT NULL, revoked_at TEXT, created_at TEXT NOT NULL,
 request_digest TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS evolution_generation_batches (
 id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, problem_fingerprint TEXT NOT NULL,
 experience_ids_json TEXT NOT NULL, base_bundle_id TEXT NOT NULL REFERENCES runtime_bundles(id),
 target_role TEXT NOT NULL, allowed_path TEXT NOT NULL, generation_config_digest TEXT NOT NULL,
 root_budget_id TEXT NOT NULL, max_calls INTEGER NOT NULL CHECK(max_calls > 0),
 budget_microusd INTEGER NOT NULL CHECK(budget_microusd > 0), deadline_at TEXT NOT NULL,
 content_authorization_id TEXT REFERENCES evolution_content_authorizations(id),
 status TEXT NOT NULL CHECK(status IN ('APPROVED','REQUESTING','COMPLETED','STOPPED','UNKNOWN')),
 calls_started INTEGER NOT NULL DEFAULT 0, candidate_id TEXT REFERENCES evolution_candidates(id), error_json TEXT,
 request_digest TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 UNIQUE(owner_id,problem_fingerprint,base_bundle_id,generation_config_digest)
);

CREATE TABLE IF NOT EXISTS canary_exposures (
      deployment_id TEXT NOT NULL, run_id TEXT NOT NULL,
      assignment_hash TEXT NOT NULL, cohort TEXT NOT NULL CHECK(cohort IN ('champion','challenger')),
      bundle_id TEXT NOT NULL, success INTEGER CHECK(success IN (0,1)),
      safety_pass INTEGER CHECK(safety_pass IN (0,1)), request_digest TEXT NOT NULL,
      idempotency_key TEXT NOT NULL UNIQUE, exposed_at TEXT NOT NULL, finished_at TEXT, quality_outcome TEXT, safety_outcome TEXT, ttft_ms INTEGER, ttft_p95_ms INTEGER, invocation_count INTEGER, attempt_count INTEGER, cost_microusd INTEGER, routing_policy_digest TEXT, profile_digest TEXT, skill_digest TEXT,
      target_role TEXT NOT NULL DEFAULT '', target_purpose TEXT NOT NULL DEFAULT '', prompt_hit INTEGER,
      PRIMARY KEY(deployment_id,run_id)
    );

CREATE TABLE IF NOT EXISTS model_profiles (
      id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, name TEXT NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('ACTIVE','DISABLED')),
      created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
      UNIQUE(owner_id,name)
    );

CREATE TABLE IF NOT EXISTS model_profile_versions (
      id TEXT PRIMARY KEY, profile_id TEXT NOT NULL, version INTEGER NOT NULL,
      provider_protocol TEXT NOT NULL CHECK(provider_protocol IN ('openai_compatible','anthropic','gemini')),
      provider_name TEXT NOT NULL, base_url TEXT NOT NULL, model_name TEXT NOT NULL, credential_env_ref TEXT NOT NULL,
      capabilities_json TEXT NOT NULL, context_window INTEGER NOT NULL, max_output_tokens INTEGER NOT NULL,
      timeout_seconds REAL NOT NULL, max_attempts INTEGER NOT NULL, config_digest TEXT NOT NULL,
      created_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ACTIVE', verified_at TEXT, verification_status TEXT NOT NULL DEFAULT 'UNVERIFIED', verification_error_kind TEXT, UNIQUE(profile_id,version), UNIQUE(profile_id,config_digest)
    );

CREATE TABLE IF NOT EXISTS model_routing_policies (
      id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, version INTEGER NOT NULL, name TEXT NOT NULL,
      roles_json TEXT NOT NULL, policy_digest TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL,
      UNIQUE(owner_id,name,version)
    );

CREATE TABLE IF NOT EXISTS model_invocations (
      id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, run_id TEXT, thread_id TEXT, turn_id TEXT, agent_task_id TEXT,
      role TEXT NOT NULL, purpose TEXT NOT NULL, runtime_bundle_id TEXT, routing_policy_id TEXT,
      routing_policy_digest TEXT NOT NULL, route_snapshot_json TEXT NOT NULL, request_digest TEXT NOT NULL,
      tool_schema_digest TEXT NOT NULL, context_snapshot_digest TEXT NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('CREATED','ROUTED','RUNNING','SUCCEEDED','FAILED','CANCELLED','BUDGET_BLOCKED')),
      selected_attempt_id TEXT, idempotency_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, finished_at TEXT
    );

CREATE TABLE IF NOT EXISTS model_attempts (
      id TEXT PRIMARY KEY, invocation_id TEXT NOT NULL, ordinal INTEGER NOT NULL,
      reason TEXT NOT NULL CHECK(reason IN ('primary','retry','fallback','repair')),
      profile_version_id TEXT NOT NULL, provider_protocol TEXT NOT NULL,
      provider_request_id TEXT, request_digest TEXT NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('STARTED','SUCCEEDED','FAILED','CANCELLED')),
      error_kind TEXT, http_status INTEGER,
      uncached_input_tokens INTEGER, cache_read_tokens INTEGER, cache_write_tokens INTEGER,
      output_tokens INTEGER, reasoning_tokens INTEGER,
      started_at TEXT NOT NULL, first_token_at TEXT, finished_at TEXT,
      usage_status TEXT NOT NULL DEFAULT 'UNAVAILABLE', usage_digest TEXT, price_snapshot_id TEXT, cost_status TEXT NOT NULL DEFAULT 'UNAVAILABLE', cost_microusd INTEGER,
      UNIQUE(invocation_id,ordinal)
    );

CREATE TABLE IF NOT EXISTS model_price_snapshots (
      id TEXT PRIMARY KEY, profile_version_id TEXT NOT NULL,
      uncached_input_rate INTEGER NOT NULL, cache_read_rate INTEGER NOT NULL, cache_write_rate INTEGER NOT NULL,
      output_rate INTEGER NOT NULL, reasoning_rate INTEGER NOT NULL,
      currency TEXT NOT NULL DEFAULT 'USD', effective_at TEXT NOT NULL, price_digest TEXT NOT NULL UNIQUE,
      created_at TEXT NOT NULL
    );

CREATE TABLE IF NOT EXISTS cost_budgets (
      owner_id TEXT NOT NULL, period_kind TEXT NOT NULL CHECK(period_kind IN ('INVOCATION','DAILY','MONTHLY')),
      period_key TEXT NOT NULL, limit_microusd INTEGER NOT NULL CHECK(limit_microusd >= 0),
      reserved_microusd INTEGER NOT NULL DEFAULT 0 CHECK(reserved_microusd >= 0),
      charged_microusd INTEGER NOT NULL DEFAULT 0 CHECK(charged_microusd >= 0),
      version INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL,
      PRIMARY KEY(owner_id,period_kind,period_key)
    );

CREATE TABLE IF NOT EXISTS cost_ledger (
      row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id TEXT NOT NULL UNIQUE, owner_id TEXT NOT NULL,
      period_kind TEXT NOT NULL, period_key TEXT NOT NULL, invocation_id TEXT NOT NULL,
      attempt_id TEXT NOT NULL, price_snapshot_id TEXT,
      entry_type TEXT NOT NULL CHECK(entry_type IN ('RESERVE','CHARGE','RELEASE','ADJUSTMENT')),
      amount_microusd INTEGER NOT NULL CHECK(amount_microusd >= 0), cost_status TEXT NOT NULL,
      reason TEXT NOT NULL DEFAULT '', idempotency_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL
    );

CREATE TABLE IF NOT EXISTS evaluation_runs (
      id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, suite_id TEXT NOT NULL, suite_digest TEXT NOT NULL,
      baseline_bundle_id TEXT NOT NULL, candidate_bundle_id TEXT NOT NULL, evaluator_digest TEXT NOT NULL,
      status TEXT NOT NULL, budget_microusd INTEGER NOT NULL, created_at TEXT NOT NULL, finished_at TEXT
    , config_json TEXT NOT NULL DEFAULT '{}', lease_owner TEXT, lease_until TEXT, cancel_requested_at TEXT, attempts INTEGER NOT NULL DEFAULT 0, updated_at TEXT, idempotency_key TEXT, request_digest TEXT, error_json TEXT);

CREATE TABLE IF NOT EXISTS evaluation_case_pairs (
      id TEXT PRIMARY KEY, evaluation_run_id TEXT NOT NULL, case_id TEXT NOT NULL,
      partition TEXT NOT NULL CHECK(partition IN ('DEV','HOLDOUT','SAFETY')), domain TEXT NOT NULL,
      input_digest TEXT NOT NULL, fixture_digest TEXT NOT NULL, execution_order TEXT NOT NULL,
      UNIQUE(evaluation_run_id,case_id)
    );

CREATE TABLE IF NOT EXISTS evaluation_arm_results (
      id TEXT PRIMARY KEY, case_pair_id TEXT NOT NULL, arm TEXT NOT NULL CHECK(arm IN ('A','B')),
      bundle_id TEXT NOT NULL, invocation_id TEXT, output_text TEXT NOT NULL,
      output_digest TEXT NOT NULL, deterministic_pass INTEGER NOT NULL, metrics_json TEXT NOT NULL,
      UNIQUE(case_pair_id,arm)
    );

CREATE TABLE IF NOT EXISTS evaluation_judgments (
      id TEXT PRIMARY KEY, case_pair_id TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('QUALITY','SAFETY')),
      judge_invocation_id TEXT, result_json TEXT NOT NULL, judgment_digest TEXT NOT NULL UNIQUE,
      created_at TEXT NOT NULL, UNIQUE(case_pair_id,kind)
    );

CREATE TABLE IF NOT EXISTS skills (
      id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, name TEXT NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('INSTALLED','ENABLED','DISABLED','UNINSTALLED')),
      default_version_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, uninstalled_at TEXT,
      UNIQUE(owner_id,name)
    );

CREATE TABLE IF NOT EXISTS skill_versions (
      id TEXT PRIMARY KEY, skill_id TEXT NOT NULL, version TEXT NOT NULL,
      package_digest TEXT NOT NULL, manifest_digest TEXT NOT NULL, manifest_json TEXT NOT NULL,
      title TEXT NOT NULL, description TEXT NOT NULL, content TEXT NOT NULL, requested_tools_json TEXT NOT NULL,
      connectors_json TEXT NOT NULL, phases_json TEXT NOT NULL, storage_path TEXT NOT NULL,
      status TEXT NOT NULL CHECK(status IN ('INSTALLED','ENABLED','DISABLED','UNINSTALLED')),
      created_at TEXT NOT NULL, UNIQUE(skill_id,version), UNIQUE(package_digest)
    );

CREATE TABLE IF NOT EXISTS skill_grants (
      id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, skill_version_id TEXT NOT NULL,
      granted_tools_json TEXT NOT NULL, grant_digest TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('ACTIVE','REVOKED')),
      version INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
      UNIQUE(owner_id,skill_version_id)
    );

CREATE TABLE IF NOT EXISTS skill_bindings (
      id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, binding_type TEXT NOT NULL CHECK(binding_type IN ('THREAD','RUN')),
      binding_id TEXT NOT NULL, version_ids_json TEXT NOT NULL, snapshot_digest TEXT NOT NULL,
      idempotency_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, grant_snapshots_json TEXT NOT NULL DEFAULT '{}',
      UNIQUE(owner_id,binding_type,binding_id)
    );

CREATE TABLE IF NOT EXISTS trusted_connectors (
      id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('ENABLED','DISABLED')),
      current_version_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(owner_id,name)
    );

CREATE TABLE IF NOT EXISTS trusted_connector_versions (
      id TEXT PRIMARY KEY, connector_id TEXT NOT NULL, version INTEGER NOT NULL,
      base_url TEXT NOT NULL, methods_json TEXT NOT NULL, paths_json TEXT NOT NULL, credential_env_ref TEXT,
      request_schema_json TEXT NOT NULL DEFAULT '{}', timeout_seconds REAL NOT NULL, max_response_bytes INTEGER NOT NULL,
      risk TEXT NOT NULL, config_digest TEXT NOT NULL UNIQUE, verified_at TEXT,
      created_at TEXT NOT NULL, UNIQUE(connector_id,version)
    );

CREATE TABLE IF NOT EXISTS skill_events (
      row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_id TEXT NOT NULL UNIQUE, owner_id TEXT NOT NULL,
      skill_id TEXT, skill_version_id TEXT, type TEXT NOT NULL, actor TEXT NOT NULL,
      data_json TEXT NOT NULL DEFAULT '{}', idempotency_key TEXT NOT NULL UNIQUE, occurred_at TEXT NOT NULL
    );

CREATE TABLE IF NOT EXISTS evaluation_events (
      row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      evaluation_run_id TEXT NOT NULL,
      seq INTEGER NOT NULL,
      type TEXT NOT NULL,
      data_json TEXT NOT NULL DEFAULT '{}',
      idempotency_key TEXT NOT NULL UNIQUE,
      occurred_at TEXT NOT NULL,
      UNIQUE(evaluation_run_id,seq)
    );

CREATE TABLE IF NOT EXISTS memory_archive_jobs (
          id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, thread_id TEXT NOT NULL,
          start_message_seq INTEGER NOT NULL, end_message_seq INTEGER NOT NULL, source_hash TEXT NOT NULL,
          prompt_version TEXT NOT NULL, tokenizer_version TEXT NOT NULL,
          status TEXT NOT NULL CHECK(status IN ('QUEUED','RUNNING','RETRY_WAIT','COMPLETED','DEAD_LETTER','LEASE_LOST')),
          available_at TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL DEFAULT 3,
          lease_owner TEXT, lease_epoch INTEGER NOT NULL DEFAULT 0, lease_until TEXT,
          last_error_code TEXT, last_error_json TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, finished_at TEXT,
          UNIQUE(owner_id,thread_id,start_message_seq,end_message_seq,source_hash,prompt_version)
        );

CREATE TABLE IF NOT EXISTS memory_context_pin_items (
          pin_invocation_id TEXT NOT NULL,
          source_type TEXT NOT NULL CHECK(source_type IN ('revision','episode','thread')), source_id TEXT NOT NULL,
          source_version TEXT NOT NULL DEFAULT '', PRIMARY KEY(pin_invocation_id,source_type,source_id)
        );

CREATE TABLE IF NOT EXISTS memory_context_pin_payloads (
          pin_invocation_id TEXT PRIMARY KEY,
          rendered TEXT NOT NULL, payload_hash TEXT NOT NULL, expires_at TEXT NOT NULL
        );

CREATE TABLE IF NOT EXISTS memory_archive_signals (
          turn_id TEXT PRIMARY KEY,
          thread_id TEXT NOT NULL,
          created_at TEXT NOT NULL
        );

CREATE TABLE IF NOT EXISTS memory_proposals (
              id TEXT PRIMARY KEY, owner_id TEXT NOT NULL,
              operation TEXT NOT NULL CHECK(operation IN ('ADD','UPDATE','ARCHIVE')),
              target_entry_id TEXT, base_revision_id TEXT,
              kind TEXT NOT NULL CHECK(kind IN ('preference','constraint','fact','decision','lesson')),
              scope_type TEXT NOT NULL CHECK(scope_type IN ('user','project')), scope_id TEXT NOT NULL DEFAULT '',
              content TEXT NOT NULL, fingerprint TEXT NOT NULL,
              evidence_refs_json TEXT NOT NULL DEFAULT '[]', evidence_hash TEXT NOT NULL DEFAULT '',
              origin TEXT NOT NULL, confidence REAL NOT NULL CHECK(confidence BETWEEN 0 AND 1),
              reason TEXT NOT NULL DEFAULT '',
              status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','ACCEPTED','REJECTED','SUPERSEDED')),
              request_idempotency_key TEXT NOT NULL, decision_idempotency_key TEXT,
              accepted_revision_id TEXT, created_at TEXT NOT NULL, decided_at TEXT, request_digest TEXT NOT NULL DEFAULT '', decision_request_digest TEXT, evidence_state TEXT NOT NULL DEFAULT 'LEGACY_UNVERIFIED' CHECK(evidence_state IN ('VERIFIED','LEGACY_UNVERIFIED','INVALID')), version INTEGER NOT NULL DEFAULT 0, accepted_content TEXT,
              UNIQUE(owner_id,request_idempotency_key), UNIQUE(owner_id,decision_idempotency_key)
            );

CREATE TABLE IF NOT EXISTS memory_audit_events (
              row_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, owner_id TEXT NOT NULL, seq INTEGER NOT NULL,
              event_id TEXT NOT NULL UNIQUE, aggregate_type TEXT NOT NULL, aggregate_id TEXT NOT NULL,
              idempotency_key TEXT NOT NULL, operation TEXT NOT NULL, actor TEXT NOT NULL,
              occurred_at TEXT NOT NULL, metadata_json TEXT NOT NULL DEFAULT '{}', request_digest TEXT NOT NULL DEFAULT '',
              UNIQUE(owner_id,seq), UNIQUE(owner_id,idempotency_key)
            );

CREATE TABLE IF NOT EXISTS memory_evidence_links (
          id TEXT PRIMARY KEY,
          aggregate_type TEXT NOT NULL CHECK(aggregate_type IN ('proposal','revision')),
          aggregate_id TEXT NOT NULL,
          source_type TEXT NOT NULL CHECK(source_type IN ('thread_message','thread_event','run_event')),
          source_id TEXT NOT NULL,
          created_at TEXT NOT NULL,
          UNIQUE(aggregate_type,aggregate_id,source_type,source_id)
        );

CREATE TABLE IF NOT EXISTS turn_metrics (turn_id TEXT PRIMARY KEY,queue_wait_ms INTEGER,context_ms INTEGER,model_ttft_ms INTEGER,stream_ms INTEGER,answer_wait_ms INTEGER,total_ms INTEGER,model_attempt_count INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);

CREATE UNIQUE INDEX uq_runs_source_turn
ON runs(source_turn_id)
WHERE source_turn_id IS NOT NULL;

CREATE INDEX idx_turn_asks_turn_status ON turn_asks(turn_id, status);

CREATE UNIQUE INDEX uq_thread_message_seq ON thread_messages(thread_id,message_seq);

CREATE UNIQUE INDEX uq_thread_message_research ON thread_messages(research_job_id) WHERE research_job_id IS NOT NULL;

CREATE UNIQUE INDEX uq_memory_active_fingerprint ON memory_entries(owner_id,scope_type,scope_id,canonical_fingerprint) WHERE status='ACTIVE';

CREATE INDEX idx_memory_entries_scope ON memory_entries(owner_id,scope_type,scope_id,status,pinned,importance,updated_at);

CREATE INDEX idx_memory_episodes_scope ON memory_episodes(owner_id,thread_id,project_id,status,created_at);

CREATE INDEX idx_research_claim ON research_jobs(status,available_at,lease_until,created_at);

CREATE INDEX idx_research_thread ON research_jobs(thread_id,created_at DESC);

CREATE INDEX idx_research_schedule ON research_jobs(schedule_id,created_at DESC);

CREATE INDEX idx_goal_programs_owner_status ON goal_programs(owner_id,status,deleted_at,updated_at);

CREATE INDEX idx_goal_actions_today ON goal_actions(program_id,status,scheduled_date,position);

CREATE UNIQUE INDEX uq_goal_action_deferred_from ON goal_actions(deferred_from_action_id) WHERE deferred_from_action_id IS NOT NULL;

CREATE INDEX idx_goal_adjustments_program ON goal_adjustment_proposals(program_id,status,created_at);

CREATE INDEX idx_goal_daily_reviews_queue ON goal_daily_reviews(status,lease_until,created_at);

CREATE INDEX idx_agent_task_claim ON agent_tasks(status,available_at,lease_until,priority,created_at);

CREATE INDEX idx_evolution_candidates_owner_status ON evolution_candidates(owner_id,status,created_at);

CREATE INDEX idx_evolution_events_candidate ON evolution_events(candidate_id,row_id);

CREATE UNIQUE INDEX uq_experience_observation ON evolution_experiences(owner_id,source_kind,source_event_id,signal_type) WHERE source_event_id <> '';

CREATE INDEX idx_experience_observer_source ON evolution_experiences(owner_id,source_kind,source_id,created_at);

CREATE INDEX idx_model_invocations_run ON model_invocations(run_id,created_at);

CREATE INDEX idx_model_invocations_thread ON model_invocations(thread_id,created_at);

CREATE INDEX idx_model_attempts_invocation ON model_attempts(invocation_id,ordinal);

CREATE INDEX idx_cost_ledger_owner_period ON cost_ledger(owner_id,period_kind,period_key,row_id);

CREATE INDEX idx_skill_events_skill ON skill_events(skill_id,row_id);

CREATE UNIQUE INDEX uq_evaluation_run_idempotency ON evaluation_runs(owner_id,idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE INDEX idx_evaluation_run_claim ON evaluation_runs(status,lease_until,created_at);

CREATE INDEX idx_runs_runtime_bundle ON runs(runtime_bundle_id);

CREATE INDEX idx_turns_runtime_bundle ON turns(runtime_bundle_id);

CREATE UNIQUE INDEX uq_cost_attempt_period_entry ON cost_ledger(attempt_id,period_kind,period_key,entry_type,COALESCE(price_snapshot_id,''));

CREATE INDEX idx_memory_archive_jobs_claim ON memory_archive_jobs(status,available_at,lease_until,created_at);

CREATE INDEX idx_memory_context_pin_source ON memory_context_pin_items(source_type,source_id);

CREATE UNIQUE INDEX uq_threads_id_owner ON threads(id,owner_id);

CREATE INDEX idx_memory_archive_signals_created ON memory_archive_signals(created_at,turn_id);

CREATE UNIQUE INDEX uq_memory_proposals_owner_request ON memory_proposals(owner_id,request_idempotency_key);

CREATE UNIQUE INDEX uq_memory_proposals_owner_decision ON memory_proposals(owner_id,decision_idempotency_key) WHERE decision_idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX uq_memory_audit_owner_key ON memory_audit_events(owner_id,idempotency_key);

CREATE INDEX idx_memory_evidence_aggregate
          ON memory_evidence_links(aggregate_type,aggregate_id,created_at,id);

CREATE UNIQUE INDEX uq_memory_pending_add_fingerprint
          ON memory_proposals(owner_id,scope_type,scope_id,fingerprint)
          WHERE operation='ADD' AND status='PENDING';

CREATE INDEX idx_turn_jobs_claim ON turn_jobs(status,lease_until,started_at);

CREATE INDEX idx_turns_thread_status ON turns(thread_id,status,id);

ALTER TABLE "runs" ADD CONSTRAINT "fk_runs_runtime_bundle_id_0" FOREIGN KEY ("runtime_bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "turns" ADD CONSTRAINT "fk_turns_runtime_bundle_id_0" FOREIGN KEY ("runtime_bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "memory_revisions" ADD CONSTRAINT "fk_memory_revisions_entry_id_0" FOREIGN KEY ("entry_id") REFERENCES "memory_entries" ("id") ON DELETE CASCADE;

ALTER TABLE "conversation_archive_state" ADD CONSTRAINT "fk_conversation_archive_state_thread_id_0" FOREIGN KEY ("thread_id") REFERENCES "threads" ("id") ON DELETE CASCADE;

ALTER TABLE "memory_episodes" ADD CONSTRAINT "fk_memory_episodes_thread_id_0" FOREIGN KEY ("thread_id") REFERENCES "threads" ("id") ON DELETE CASCADE;

ALTER TABLE "research_jobs" ADD CONSTRAINT "fk_research_jobs_retry_of_job_id_0" FOREIGN KEY ("retry_of_job_id") REFERENCES "research_jobs" ("id");

ALTER TABLE "research_jobs" ADD CONSTRAINT "fk_research_jobs_source_turn_id_1" FOREIGN KEY ("source_turn_id") REFERENCES "turns" ("id");

ALTER TABLE "research_jobs" ADD CONSTRAINT "fk_research_jobs_thread_id_2" FOREIGN KEY ("thread_id") REFERENCES "threads" ("id");

ALTER TABLE "research_job_attempts" ADD CONSTRAINT "fk_research_job_attempts_job_id_0" FOREIGN KEY ("job_id") REFERENCES "research_jobs" ("id") ON DELETE CASCADE;

ALTER TABLE "research_reports" ADD CONSTRAINT "fk_research_reports_job_id_0" FOREIGN KEY ("job_id") REFERENCES "research_jobs" ("id") ON DELETE CASCADE;

ALTER TABLE "research_sources" ADD CONSTRAINT "fk_research_sources_job_id_0" FOREIGN KEY ("job_id") REFERENCES "research_jobs" ("id") ON DELETE CASCADE;

ALTER TABLE "research_evidence" ADD CONSTRAINT "fk_research_evidence_source_id_0" FOREIGN KEY ("source_id") REFERENCES "research_sources" ("id") ON DELETE CASCADE;

ALTER TABLE "research_evidence" ADD CONSTRAINT "fk_research_evidence_job_id_1" FOREIGN KEY ("job_id") REFERENCES "research_jobs" ("id") ON DELETE CASCADE;

ALTER TABLE "research_sections" ADD CONSTRAINT "fk_research_sections_job_id_0" FOREIGN KEY ("job_id") REFERENCES "research_jobs" ("id") ON DELETE CASCADE;

ALTER TABLE "research_schedules" ADD CONSTRAINT "fk_research_schedules_thread_id_0" FOREIGN KEY ("thread_id") REFERENCES "threads" ("id");

ALTER TABLE "notification_deliveries" ADD CONSTRAINT "fk_notification_deliveries_channel_id_0" FOREIGN KEY ("channel_id") REFERENCES "notification_channels" ("id") ON DELETE CASCADE;

ALTER TABLE "notification_deliveries" ADD CONSTRAINT "fk_notification_deliveries_job_id_1" FOREIGN KEY ("job_id") REFERENCES "research_jobs" ("id") ON DELETE CASCADE;

ALTER TABLE "goal_programs" ADD CONSTRAINT "fk_goal_programs_source_plan_document_version_id_0" FOREIGN KEY ("source_plan_document_version_id") REFERENCES "plan_document_versions" ("id");

ALTER TABLE "goal_programs" ADD CONSTRAINT "fk_goal_programs_source_plan_document_id_1" FOREIGN KEY ("source_plan_document_id") REFERENCES "plan_documents" ("id");

ALTER TABLE "goal_programs" ADD CONSTRAINT "fk_goal_programs_source_thread_id_2" FOREIGN KEY ("source_thread_id") REFERENCES "threads" ("id");

ALTER TABLE "goal_program_versions" ADD CONSTRAINT "fk_goal_program_versions_source_plan_document_version_id_0" FOREIGN KEY ("source_plan_document_version_id") REFERENCES "plan_document_versions" ("id");

ALTER TABLE "goal_program_versions" ADD CONSTRAINT "fk_goal_program_versions_base_version_id_1" FOREIGN KEY ("base_version_id") REFERENCES "goal_program_versions" ("id");

ALTER TABLE "goal_program_versions" ADD CONSTRAINT "fk_goal_program_versions_program_id_2" FOREIGN KEY ("program_id") REFERENCES "goal_programs" ("id");

ALTER TABLE "goal_actions" ADD CONSTRAINT "fk_goal_actions_deferred_from_action_id_0" FOREIGN KEY ("deferred_from_action_id") REFERENCES "goal_actions" ("id");

ALTER TABLE "goal_actions" ADD CONSTRAINT "fk_goal_actions_program_version_id_1" FOREIGN KEY ("program_version_id") REFERENCES "goal_program_versions" ("id");

ALTER TABLE "goal_actions" ADD CONSTRAINT "fk_goal_actions_program_id_2" FOREIGN KEY ("program_id") REFERENCES "goal_programs" ("id");

ALTER TABLE "goal_action_feedback" ADD CONSTRAINT "fk_goal_action_feedback_action_id_0" FOREIGN KEY ("action_id") REFERENCES "goal_actions" ("id");

ALTER TABLE "goal_program_events" ADD CONSTRAINT "fk_goal_program_events_action_id_0" FOREIGN KEY ("action_id") REFERENCES "goal_actions" ("id");

ALTER TABLE "goal_program_events" ADD CONSTRAINT "fk_goal_program_events_program_id_1" FOREIGN KEY ("program_id") REFERENCES "goal_programs" ("id");

ALTER TABLE "goal_adjustment_proposals" ADD CONSTRAINT "fk_goal_adjustment_proposals_plan_sync_version_id_0" FOREIGN KEY ("plan_sync_version_id") REFERENCES "plan_document_versions" ("id");

ALTER TABLE "goal_adjustment_proposals" ADD CONSTRAINT "fk_goal_adjustment_proposals_accepted_program_version_id_1" FOREIGN KEY ("accepted_program_version_id") REFERENCES "goal_program_versions" ("id");

ALTER TABLE "goal_adjustment_proposals" ADD CONSTRAINT "fk_goal_adjustment_proposals_expected_plan_document_version_id_2" FOREIGN KEY ("expected_plan_document_version_id") REFERENCES "plan_document_versions" ("id");

ALTER TABLE "goal_adjustment_proposals" ADD CONSTRAINT "fk_goal_adjustment_proposals_base_program_version_id_3" FOREIGN KEY ("base_program_version_id") REFERENCES "goal_program_versions" ("id");

ALTER TABLE "goal_adjustment_proposals" ADD CONSTRAINT "fk_goal_adjustment_proposals_program_id_4" FOREIGN KEY ("program_id") REFERENCES "goal_programs" ("id");

ALTER TABLE "goal_daily_reviews" ADD CONSTRAINT "fk_goal_daily_reviews_proposal_id_0" FOREIGN KEY ("proposal_id") REFERENCES "goal_adjustment_proposals" ("id");

ALTER TABLE "goal_daily_reviews" ADD CONSTRAINT "fk_goal_daily_reviews_program_id_1" FOREIGN KEY ("program_id") REFERENCES "goal_programs" ("id");

ALTER TABLE "goal_review_action_snapshots" ADD CONSTRAINT "fk_goal_review_action_snapshots_action_id_0" FOREIGN KEY ("action_id") REFERENCES "goal_actions" ("id");

ALTER TABLE "goal_review_action_snapshots" ADD CONSTRAINT "fk_goal_review_action_snapshots_review_id_1" FOREIGN KEY ("review_id") REFERENCES "goal_daily_reviews" ("id") ON DELETE CASCADE;

ALTER TABLE "runtime_channels" ADD CONSTRAINT "fk_runtime_channels_bundle_id_0" FOREIGN KEY ("bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "agent_context_snapshots" ADD CONSTRAINT "fk_agent_context_snapshots_runtime_bundle_id_0" FOREIGN KEY ("runtime_bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "agent_runs" ADD CONSTRAINT "fk_agent_runs_runtime_bundle_id_0" FOREIGN KEY ("runtime_bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "agent_runs" ADD CONSTRAINT "fk_agent_runs_context_snapshot_id_1" FOREIGN KEY ("context_snapshot_id") REFERENCES "agent_context_snapshots" ("id");

ALTER TABLE "agent_tasks" ADD CONSTRAINT "fk_agent_tasks_context_snapshot_id_0" FOREIGN KEY ("context_snapshot_id") REFERENCES "agent_context_snapshots" ("id");

ALTER TABLE "agent_tasks" ADD CONSTRAINT "fk_agent_tasks_parent_task_id_1" FOREIGN KEY ("parent_task_id") REFERENCES "agent_tasks" ("id");

ALTER TABLE "agent_tasks" ADD CONSTRAINT "fk_agent_tasks_agent_run_id_2" FOREIGN KEY ("agent_run_id") REFERENCES "agent_runs" ("id") ON DELETE CASCADE;

ALTER TABLE "agent_task_attempts" ADD CONSTRAINT "fk_agent_task_attempts_task_id_0" FOREIGN KEY ("task_id") REFERENCES "agent_tasks" ("id") ON DELETE CASCADE;

ALTER TABLE "agent_task_checkpoints" ADD CONSTRAINT "fk_agent_task_checkpoints_task_id_0" FOREIGN KEY ("task_id") REFERENCES "agent_tasks" ("id") ON DELETE CASCADE;

ALTER TABLE "agent_artifacts" ADD CONSTRAINT "fk_agent_artifacts_task_id_0" FOREIGN KEY ("task_id") REFERENCES "agent_tasks" ("id") ON DELETE CASCADE;

ALTER TABLE "agent_events" ADD CONSTRAINT "fk_agent_events_agent_run_id_0" FOREIGN KEY ("agent_run_id") REFERENCES "agent_runs" ("id") ON DELETE CASCADE;

ALTER TABLE "evolution_experiences" ADD CONSTRAINT "fk_evolution_experiences_runtime_bundle_id_0" FOREIGN KEY ("runtime_bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "evolution_candidates" ADD CONSTRAINT "fk_evolution_candidates_target_bundle_id_0" FOREIGN KEY ("target_bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "evolution_candidates" ADD CONSTRAINT "fk_evolution_candidates_base_bundle_id_1" FOREIGN KEY ("base_bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "evolution_evaluations" ADD CONSTRAINT "fk_evolution_evaluations_candidate_bundle_id_0" FOREIGN KEY ("candidate_bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "evolution_evaluations" ADD CONSTRAINT "fk_evolution_evaluations_baseline_bundle_id_1" FOREIGN KEY ("baseline_bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "evolution_evaluations" ADD CONSTRAINT "fk_evolution_evaluations_candidate_id_2" FOREIGN KEY ("candidate_id") REFERENCES "evolution_candidates" ("id");

ALTER TABLE "evolution_decisions" ADD CONSTRAINT "fk_evolution_decisions_evaluation_id_0" FOREIGN KEY ("evaluation_id") REFERENCES "evolution_evaluations" ("id");

ALTER TABLE "evolution_decisions" ADD CONSTRAINT "fk_evolution_decisions_candidate_id_1" FOREIGN KEY ("candidate_id") REFERENCES "evolution_candidates" ("id");

ALTER TABLE "canary_deployments" ADD CONSTRAINT "fk_canary_deployments_challenger_bundle_id_0" FOREIGN KEY ("challenger_bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "canary_deployments" ADD CONSTRAINT "fk_canary_deployments_champion_bundle_id_1" FOREIGN KEY ("champion_bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "canary_deployments" ADD CONSTRAINT "fk_canary_deployments_approval_id_2" FOREIGN KEY ("approval_id") REFERENCES "evolution_decisions" ("id");

ALTER TABLE "canary_deployments" ADD CONSTRAINT "fk_canary_deployments_candidate_id_3" FOREIGN KEY ("candidate_id") REFERENCES "evolution_candidates" ("id");

ALTER TABLE "canary_exposures" ADD CONSTRAINT "fk_canary_exposures_bundle_id_0" FOREIGN KEY ("bundle_id") REFERENCES "runtime_bundles" ("id");

ALTER TABLE "canary_exposures" ADD CONSTRAINT "fk_canary_exposures_deployment_id_1" FOREIGN KEY ("deployment_id") REFERENCES "canary_deployments" ("id");

ALTER TABLE "model_profile_versions" ADD CONSTRAINT "fk_model_profile_versions_profile_id_0" FOREIGN KEY ("profile_id") REFERENCES "model_profiles" ("id");

ALTER TABLE "model_attempts" ADD CONSTRAINT "fk_model_attempts_price_snapshot_id_0" FOREIGN KEY ("price_snapshot_id") REFERENCES "model_price_snapshots" ("id");

ALTER TABLE "model_attempts" ADD CONSTRAINT "fk_model_attempts_profile_version_id_1" FOREIGN KEY ("profile_version_id") REFERENCES "model_profile_versions" ("id");

ALTER TABLE "model_attempts" ADD CONSTRAINT "fk_model_attempts_invocation_id_2" FOREIGN KEY ("invocation_id") REFERENCES "model_invocations" ("id");

ALTER TABLE "model_price_snapshots" ADD CONSTRAINT "fk_model_price_snapshots_profile_version_id_0" FOREIGN KEY ("profile_version_id") REFERENCES "model_profile_versions" ("id");

ALTER TABLE "evaluation_case_pairs" ADD CONSTRAINT "fk_evaluation_case_pairs_evaluation_run_id_0" FOREIGN KEY ("evaluation_run_id") REFERENCES "evaluation_runs" ("id");

ALTER TABLE "evaluation_arm_results" ADD CONSTRAINT "fk_evaluation_arm_results_invocation_id_0" FOREIGN KEY ("invocation_id") REFERENCES "model_invocations" ("id");

ALTER TABLE "evaluation_arm_results" ADD CONSTRAINT "fk_evaluation_arm_results_case_pair_id_1" FOREIGN KEY ("case_pair_id") REFERENCES "evaluation_case_pairs" ("id");

ALTER TABLE "evaluation_judgments" ADD CONSTRAINT "fk_evaluation_judgments_judge_invocation_id_0" FOREIGN KEY ("judge_invocation_id") REFERENCES "model_invocations" ("id");

ALTER TABLE "evaluation_judgments" ADD CONSTRAINT "fk_evaluation_judgments_case_pair_id_1" FOREIGN KEY ("case_pair_id") REFERENCES "evaluation_case_pairs" ("id");

ALTER TABLE "skill_versions" ADD CONSTRAINT "fk_skill_versions_skill_id_0" FOREIGN KEY ("skill_id") REFERENCES "skills" ("id");

ALTER TABLE "skill_grants" ADD CONSTRAINT "fk_skill_grants_skill_version_id_0" FOREIGN KEY ("skill_version_id") REFERENCES "skill_versions" ("id");

ALTER TABLE "trusted_connector_versions" ADD CONSTRAINT "fk_trusted_connector_versions_connector_id_0" FOREIGN KEY ("connector_id") REFERENCES "trusted_connectors" ("id");

ALTER TABLE "evaluation_events" ADD CONSTRAINT "fk_evaluation_events_evaluation_run_id_0" FOREIGN KEY ("evaluation_run_id") REFERENCES "evaluation_runs" ("id");

ALTER TABLE "memory_archive_jobs" ADD CONSTRAINT "fk_memory_archive_jobs_thread_id_0" FOREIGN KEY ("thread_id") REFERENCES "threads" ("id") ON DELETE CASCADE;

ALTER TABLE "memory_context_pin_items" ADD CONSTRAINT "fk_memory_context_pin_items_pin_invocation_id_0" FOREIGN KEY ("pin_invocation_id") REFERENCES "memory_context_pins" ("model_invocation_id") ON DELETE CASCADE;

ALTER TABLE "memory_context_pin_payloads" ADD CONSTRAINT "fk_memory_context_pin_payloads_pin_invocation_id_0" FOREIGN KEY ("pin_invocation_id") REFERENCES "memory_context_pins" ("model_invocation_id") ON DELETE CASCADE;

ALTER TABLE "memory_archive_signals" ADD CONSTRAINT "fk_memory_archive_signals_thread_id_0" FOREIGN KEY ("thread_id") REFERENCES "threads" ("id") ON DELETE CASCADE;

ALTER TABLE "memory_archive_signals" ADD CONSTRAINT "fk_memory_archive_signals_turn_id_1" FOREIGN KEY ("turn_id") REFERENCES "turns" ("id") ON DELETE CASCADE;

ALTER TABLE "turn_metrics" ADD CONSTRAINT "fk_turn_metrics_turn_id_0" FOREIGN KEY ("turn_id") REFERENCES "turns" ("id");

CREATE TABLE IF NOT EXISTS turn_tool_calls (
    id TEXT PRIMARY KEY,
    turn_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    tool_name TEXT NOT NULL,
    params_json TEXT NOT NULL,
    params_hash TEXT NOT NULL,
    risk TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING_APPROVAL',
    approval_id TEXT,
    binding_json TEXT NOT NULL DEFAULT '{}',
    result_json TEXT,
    error_code TEXT,
    continuation_turn_id TEXT,
    decision_idempotency_key TEXT UNIQUE,
    created_at TEXT NOT NULL,
    acted_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_turn_tool_calls_turn ON turn_tool_calls(turn_id, status);
CREATE INDEX IF NOT EXISTS idx_turn_tool_calls_continuation ON turn_tool_calls(continuation_turn_id);
