import { useEffect, useState } from "react";
import { confirmSkillInstall, listInstalledSkills, listSkillVersions, listTrustedConnectors, previewSkillInstall, setSkillVersionEnabled, uninstallSkill } from "../api";
import type { SkillDefinition, SkillInstallPreview, SkillVersionRecord, TrustedConnectorRecord } from "../types";
import AppToast from "../components/AppToast";
import ConfirmDialog from "../components/ConfirmDialog";

export default function SkillsPage({csrfToken}:{csrfToken:string}){
  const [skills,setSkills]=useState<SkillDefinition[]>([]),[connectors,setConnectors]=useState<TrustedConnectorRecord[]>([]),[selected,setSelected]=useState<SkillDefinition|null>(null),[versions,setVersions]=useState<SkillVersionRecord[]>([]);
  const [preview,setPreview]=useState<SkillInstallPreview|null>(null),[grants,setGrants]=useState<string[]>([]),[busy,setBusy]=useState(""),[error,setError]=useState(""),[remove,setRemove]=useState<SkillDefinition|null>(null),[notice,setNotice]=useState<{message:string;tone:"success"|"error"}|null>(null);
  const load=()=>Promise.all([listInstalledSkills(),listTrustedConnectors()]).then(([s,c])=>{setSkills(s.skills);setConnectors(c.connectors);setError("");}).catch(e=>setError(e instanceof Error?e.message:"Skill 数据加载失败"));
  useEffect(()=>{void load();},[]);
  async function choose(skill:SkillDefinition){setSelected(skill);if(skill.skill_id){try{const result=await listSkillVersions(skill.skill_id);setVersions(result.versions);}catch{setVersions([])}}}
  async function toggle(v:SkillVersionRecord){try{const next=await setSkillVersionEnabled(v.version_id,v.status!=="ENABLED",csrfToken);setVersions(items=>items.map(x=>x.version_id===next.version_id?next:x));setNotice({message:next.status==="ENABLED"?"Skill 已启用":"Skill 已停用",tone:"success"});}catch(e){setNotice({message:e instanceof Error?e.message:"操作失败",tone:"error"});}}
  async function selectZip(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;setBusy("preview");try{const result=await previewSkillInstall(file,csrfToken);setPreview(result);setGrants([]);setNotice({message:"ZIP 校验通过，请确认工具权限",tone:"success"});}catch(e){setNotice({message:e instanceof Error?e.message:"Skill ZIP 校验失败",tone:"error"});}finally{setBusy("");}}
  async function install(){if(!preview)return;setBusy("install");try{await confirmSkillInstall(preview.install_token,grants,csrfToken);setPreview(null);setGrants([]);await load();setNotice({message:"Skill 已安装并固定版本",tone:"success"});}catch(e){setNotice({message:e instanceof Error?e.message:"Skill 安装失败",tone:"error"});}finally{setBusy("");}}
  async function confirmRemove(){if(!remove?.skill_id)return;setBusy("remove");try{await uninstallSkill(remove.skill_id,csrfToken);if(selected?.skill_id===remove.skill_id){setSelected(null);setVersions([]);}setRemove(null);await load();setNotice({message:"Skill 已卸载",tone:"success"});}catch(e){setRemove(null);setNotice({message:e instanceof Error?e.message:"Skill 卸载失败",tone:"error"});}finally{setBusy("");}}
  return <section className="control-page"><header className="control-hero"><div><span className="eyebrow">VERSIONED SKILLS</span><h2>Skill 平台</h2><p>声明式 ZIP、内容寻址版本、五层权限交集与可信 HTTPS Connector。</p></div><div className="control-hero-metrics"><strong>{skills.length}</strong><span>已安装</span><strong>{connectors.length}</strong><span>Connector</span></div></header>
  {error&&<div className="control-alert" role="alert">{error}</div>}
  <section className="control-panel control-create"><div className="control-panel-head"><div><span className="eyebrow">INSTALL</span><h3>安装或更新 Skill</h3></div></div><p className="control-helper">选择 ZIP 后只做安全校验与权限预览；你确认授权后才会安装。</p><label className="file-control">选择 Skill ZIP<input aria-label="选择 Skill ZIP" type="file" accept=".zip,application/zip" disabled={!csrfToken||Boolean(busy)} onChange={selectZip}/></label>
  {preview&&<div className="permission-preview"><div><span className="eyebrow">PERMISSION DIFF</span><h4>{preview.title} · {preview.version}</h4><p>{preview.description}</p></div><div><strong>请求的工具权限</strong>{preview.requested_tools.length?<div className="permission-checks">{preview.requested_tools.map(tool=><label key={tool}><input type="checkbox" aria-label={tool} checked={grants.includes(tool)} onChange={e=>setGrants(e.target.checked?[...grants,tool]:grants.filter(item=>item!==tool))}/><span>{tool}</span></label>)}</div>:<p>此版本为 Prompt-only，不申请工具权限。</p>}</div><dl className="detail-list"><div><dt>执行阶段</dt><dd>{preview.phases.join(" · ")||"无"}</dd></div><div><dt>Connector</dt><dd>{preview.connectors.join(" · ")||"无"}</dd></div><div><dt>包摘要</dt><dd><code>{preview.package_digest.slice(0,16)}</code></dd></div></dl><div className="control-actions"><button className="button button-secondary" type="button" onClick={()=>setPreview(null)}>取消</button><button className="button button-primary" disabled={busy==="install"} type="button" onClick={()=>void install()}>{busy==="install"?"安装中…":"确认安装"}</button></div></div>}
  </section>
  <div className="control-master-detail"><section className="control-panel control-master"><div className="control-panel-head"><div><span className="eyebrow">INSTALLED</span><h3>已安装 Skill</h3></div></div>{!skills.length?<div className="control-empty compact"><h3>暂无 Skill</h3><p>安装 ZIP 后先预览权限，再确认授权。</p></div>:skills.map(s=><button className={`control-select-row${selected?.name===s.name?" active":""}`} key={s.name} onClick={()=>void choose(s)}><span><strong>{s.title}</strong><small>{s.description}</small></span><span className={s.enabled?"signal-good":"signal-warn"}>{s.enabled?"启用":"停用"}</span></button>)}</section><section className="control-panel control-detail">{!selected?<div className="control-empty"><h3>选择一个 Skill</h3><p>查看固定版本、工具授权、执行阶段和 Connector 引用。</p></div>:<><div className="control-panel-head"><div><span className="eyebrow">SKILL DETAIL</span><h3>{selected.title}</h3></div><button className="button button-danger" type="button" onClick={()=>setRemove(selected)}>卸载 Skill</button></div>{versions.map(v=><article className="skill-version-card" key={v.version_id}><div className="control-row-title"><strong>版本 {v.version}</strong><span className={`status-chip status-${v.status.toLowerCase()}`}>{v.status}</span></div><p>已授权工具 {v.granted_tools.length} / {v.requested_tools.length}</p><div className="chip-row">{v.requested_tools.length?v.requested_tools.map(t=><span className={v.granted_tools.includes(t)?"data-chip granted":"data-chip"} key={t}>{t}</span>):<span className="data-chip">Prompt-only</span>}</div><dl className="detail-list"><div><dt>执行阶段</dt><dd>{v.phases.join(" · ")||"无"}</dd></div><div><dt>Connector</dt><dd>{v.connectors.join(" · ")||"无"}</dd></div><div><dt>包摘要</dt><dd><code>{v.package_digest.slice(0,16)}</code></dd></div></dl><button className="button button-secondary" onClick={()=>void toggle(v)}>{v.status==="ENABLED"?"停用版本":"启用版本"}</button></article>)}</>}</section></div>
  <section className="control-panel connector-panel"><div className="control-panel-head"><div><span className="eyebrow">TRUSTED HTTPS</span><h3>可信 Connector</h3></div><span className="control-count">{connectors.length}</span></div>{connectors.length?<div className="control-list">{connectors.map(c=><article className="control-row" key={c.version_id}><div><strong>{c.name} · v{c.version}</strong><p>{c.base_url}</p><div className="chip-row">{c.methods.map(m=><span className="data-chip" key={m}>{m}</span>)}</div></div><span className={c.verified_at?"signal-good":"signal-warn"}>{c.verified_at?"DNS 已验证":"待验证"}</span></article>)}</div>:<div className="control-empty compact"><h3>暂无 Connector</h3><p>Skill 不能直接声明任意 URL，只能引用这里维护的 HTTPS 连接器。</p></div>}</section>
  <ConfirmDialog open={Boolean(remove)} title="卸载 Skill？" description={`卸载“${remove?.title??""}”会阻止新会话使用它，既有运行仍保留固定版本用于审计。`} confirmLabel="确认卸载" busy={busy==="remove"} onCancel={()=>setRemove(null)} onConfirm={()=>void confirmRemove()}/>{notice&&<AppToast {...notice} onDismiss={()=>setNotice(null)}/>}</section>;
}
