import { useEffect, useState } from "react";
import { getCostSummary, getUsageSummary, setCostBudget } from "../api";
import type { CostSummary, UsageGroup } from "../types";
import AppToast from "../components/AppToast";
import { localizedCode } from "../localization";

const money=(v:number)=>`$${(v/1_000_000).toFixed(6)}`;
const periodKey=(kind:string)=>kind==="MONTHLY"?new Date().toISOString().slice(0,7):kind==="DAILY"?new Date().toISOString().slice(0,10):"default";
const metric=(value:number|null,suffix="")=>value===null?"不可用":`${value.toFixed(2)}${suffix}`;

export default function UsagePage({csrfToken=""}:{csrfToken?:string}){
  const [budgets,setBudgets]=useState<Record<string,CostSummary|undefined>>({}),[groups,setGroups]=useState<UsageGroup[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[notice,setNotice]=useState<{message:string;tone:"success"|"error"}|null>(null),[limits,setLimits]=useState<Record<string,string>>({});
  async function load(){const settled=await Promise.all(["INVOCATION","DAILY","MONTHLY"].map(async kind=>{try{return[kind,await getCostSummary(kind,periodKey(kind))] as const}catch{return[kind,undefined] as const}}));const usage=await getUsageSummary();const next=Object.fromEntries(settled);setBudgets(next);setLimits(Object.fromEntries(settled.map(([kind,value])=>[kind,String(value?.limit_microusd??"")])));setGroups(usage.groups);}
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"用量加载失败")).finally(()=>setLoading(false));},[]);
  async function save(kind:string,e:React.FormEvent){e.preventDefault();setBusy(kind);try{const value=await setCostBudget(Number(limits[kind]),csrfToken,kind,periodKey(kind));setBudgets({...budgets,[kind]:value});setNotice({message:`${localizedCode(kind, kind)}预算已保存`,tone:"success"});}catch(err){setNotice({message:err instanceof Error?err.message:"预算保存失败",tone:"error"});}finally{setBusy("");}}
  const daily=budgets.DAILY,used=daily?(daily.charged_microusd+daily.reserved_microusd):0;
  return <section className="control-page" aria-busy={loading}><header className="control-hero"><div><span className="eyebrow">用量账本</span><h2>用量与预算</h2><p>费用与性能来自后端权威账本。未知费用保持“不可用”，浏览器不会重新估算。</p></div></header>{error&&<div className="control-alert" role="alert">{error}</div>}
  {daily&&<div className="metric-grid"><article><span>今日已结算</span><strong>{money(daily.charged_microusd)}</strong><small>真实 Attempt 结算</small></article><article><span>今日已预留</span><strong>{money(daily.reserved_microusd)}</strong><small>进行中的最坏情况预留</small></article><article><span>今日上限</span><strong>{money(daily.limit_microusd)}</strong><small>网络请求前预算门禁</small></article><article><span>今日剩余</span><strong>{money(Math.max(daily.limit_microusd-used,0))}</strong><small>扣除结算与预留</small></article></div>}
  <section className="control-panel"><div className="control-panel-head"><div><span className="eyebrow">预算层级</span><h3>三层预算门禁</h3></div></div><div className="budget-layer-grid">{["INVOCATION","DAILY","MONTHLY"].map(kind=><form className="inline-control-form" key={kind} onSubmit={e=>void save(kind,e)}><label>{localizedCode(kind, kind)}上限（microusd）<input type="number" min="0" value={limits[kind]??""} onChange={e=>setLimits({...limits,[kind]:e.target.value})} placeholder="未配置即不限额"/></label><small>{budgets[kind]?`已结算 ${money(budgets[kind]!.charged_microusd)} · 已预留 ${money(budgets[kind]!.reserved_microusd)}`:"当前未配置"}</small><button className="button button-primary" disabled={!csrfToken||busy===kind}>{busy===kind?"保存中…":"保存预算"}</button></form>)}</div></section>
  <section className="control-panel"><div className="control-panel-head"><div><span className="eyebrow">模型指标</span><h3>按角色、供应商与模型统计</h3></div><span className="control-count">{groups.length}</span></div>{groups.length?<div className="usage-table" role="table"><div className="usage-table-row usage-table-head" role="row"><span>角色 / 模型</span><span>成功率</span><span>备用率</span><span>首字延迟</span><span>生成速度</span><span>P95 延迟</span><span>费用</span></div>{groups.map(g=><div className="usage-table-row" role="row" key={`${g.role}:${g.profile_version_id}`}><span><strong>{localizedCode(g.role, g.role)}</strong><small>{g.provider} · {g.profile_version_id.slice(-8)}</small></span><span>{(g.success_rate*100).toFixed(1)}%</span><span>{(g.fallback_rate*100).toFixed(1)}%</span><span>{metric(g.ttft_seconds,"s")}</span><span>{metric(g.tps)}</span><span>{metric(g.p95_latency_seconds,"s")}</span><span>{money(g.cost_microusd)}{g.unknown_cost_attempts>0&&<small>{g.unknown_cost_attempts} 次不可用</small>}</span></div>)}</div>:<div className="control-empty compact"><h3>暂无模型调用</h3><p>完成一次模型请求后，这里会显示权威指标。</p></div>}</section>
  {notice&&<AppToast {...notice} onDismiss={()=>setNotice(null)}/>}</section>;
}
