const labels: Record<string, string> = {
  ACCEPTED: "已接受",
  ACTIVE: "已启用",
  APPROVED: "已批准",
  BLOCKED: "已暂停",
  CANCELLED: "已取消",
  CANARY: "小范围验证中",
  COMPLETED: "已完成",
  CONFLICT: "存在冲突",
  DISABLED: "已停用",
  DRAFT: "草稿",
  ENABLED: "已启用",
  FAILED: "失败",
  INSTALLED: "已安装",
  PENDING: "等待处理",
  PAUSED: "已暂停",
  PROMOTED: "已正式启用",
  QUEUED: "等待执行",
  READY: "已就绪",
  REJECTED: "已拒绝",
  ROLLED_BACK: "已回滚",
  RUNNING: "执行中",
  STALE: "已失效",
  UNINSTALLED: "已卸载",
  BUDGET_BLOCKED: "预算不足，已暂停",
  COMMITTED: "已同步",
  IDLE: "空闲",
  RAW_REFERENCE: "原始参考",
  SCHEDULED: "待执行",
  SKIPPED: "已跳过",
  VERIFIED: "已验证",
  invocation: "单次调用",
  INVOCATION: "单次调用",
  daily: "每日",
  DAILY: "每日",
  monthly: "每月",
  MONTHLY: "每月",
  ask: "询问",
  conversation: "对话",
  coordinator: "协调",
  executor: "执行",
  expert: "专家协作",
  execution: "执行",
  planner: "规划",
  planning: "规划",
  react: "执行判断",
  reflector: "复盘",
  reflection: "复盘",
  researcher: "研究",
  critic: "审查",
  judge_quality: "质量评审",
  judge_safety: "安全评审",
  preference: "偏好",
  constraint: "约束",
  fact: "事实",
  decision: "决定",
  lesson: "经验",
  user: "用户",
  project: "项目",
  always: "始终使用",
  semantic: "按需使用",
  sensitive: "敏感",
  normal: "普通",
  ready: "已就绪",
  failed: "失败",
  pending: "待执行",
  in_progress: "执行中",
  completed: "已完成",
  cancelled: "已取消",
  conversation_domain: "对话",
  plan: "计划",
  research: "研究",
  tool: "工具",
  memory: "记忆",
  quality: "质量",
  cost: "成本",
  latency: "延迟",
  always_include: "始终使用",
  semantic_retrieval: "按需检索",
  normal_sensitivity: "普通",
};

// 运行状态词表（外壳共享层）：同一运行状态在外壳不同位置沿用既有措辞，按调用点分表维护。
// 各调用点：runStateLabels → App 顶栏 state-pill 与 WorkspaceSidebar 当前目标卡片；
// runStateStatsLabels → StatsBar「当前状态」；runStateActivityLabels → ActivityRail 运行侧栏；
// threadTurnStateLabels → ActivityRail 会话轮次状态。未命中的键回退为原始值。
export const runStateLabels: Record<string, string> = {
  RECEIVED: "等待输入",
  CLARIFYING: "需要澄清",
  PLANNING: "生成计划中",
  AWAITING_APPROVAL: "等待审批",
  EXECUTING: "执行中",
  AWAITING_OUTCOME: "等待结果",
  REFLECTING: "复盘中",
  COMPLETED: "已完成",
  BLOCKED: "已阻塞",
  FAILED: "运行失败",
  CANCELLED: "已取消",
};

export const runStateStatsLabels: Record<string, string> = {
  RECEIVED: "已收到目标",
  CLARIFYING: "正在澄清",
  PLANNING: "正在规划",
  AWAITING_APPROVAL: "等待审批",
  EXECUTING: "执行中",
  AWAITING_OUTCOME: "等待结果",
  REFLECTING: "复盘中",
  COMPLETED: "已完成",
  BLOCKED: "已阻塞",
  FAILED: "运行失败",
  CANCELLED: "已取消",
};

export const runStateActivityLabels: Record<string, string> = {
  RECEIVED: "已收到目标",
  CLARIFYING: "正在澄清目标",
  PLANNING: "正在生成计划",
  AWAITING_APPROVAL: "等待你的审批",
  EXECUTING: "正在执行计划",
  AWAITING_OUTCOME: "等待外部结果",
  REFLECTING: "正在复盘记忆",
  COMPLETED: "目标已完成",
  BLOCKED: "需要处理后继续",
  FAILED: "运行失败",
  CANCELLED: "运行已取消",
};

export const threadTurnStateLabels: Record<string, string> = {
  ACCEPTED: "已收到消息",
  ROUTING: "正在判断下一步",
  STREAMING: "正在生成回答",
  AWAITING_INPUT: "等待你的回答",
  COMPLETED: "本轮对话完成",
  AWAITING_DIRECTION: "等待你的选择",
  MATERIALIZING: "正在创建执行任务",
  FAILED: "本轮对话未完成",
  CANCELLED: "本轮对话已停止",
};

export function localizedCode(value: unknown, fallback = "未知状态"): string {
  const key = String(value ?? "").trim();
  return labels[key] ?? fallback;
}

export function localizedList(values: unknown[], fallback = "无"): string {
  if (!values.length) return fallback;
  return values.map((value) => localizedCode(value, String(value))).join(" · ");
}
