const labels: Record<string, string> = {
  ACCEPTED: "已接受",
  ACTIVE: "已启用",
  APPROVED: "已批准",
  BLOCKED: "已暂停",
  CANCELLED: "已取消",
  CANARY: "小范围验证中",
  COMPLETED: "已完成",
  CONFLICT: "存在冲突",
  DISABLED: "已停用",
  DRAFT: "草稿",
  ENABLED: "已启用",
  FAILED: "失败",
  INSTALLED: "已安装",
  PENDING: "等待处理",
  PAUSED: "已暂停",
  PROMOTED: "已正式启用",
  QUEUED: "等待执行",
  READY: "已就绪",
  REJECTED: "已拒绝",
  ROLLED_BACK: "已回滚",
  RUNNING: "执行中",
  STALE: "已失效",
  UNINSTALLED: "已卸载",
  BUDGET_BLOCKED: "预算不足，已暂停",
  COMMITTED: "已同步",
  IDLE: "空闲",
  RAW_REFERENCE: "原始参考",
  SCHEDULED: "待执行",
  SKIPPED: "已跳过",
  VERIFIED: "已验证",
  invocation: "单次调用",
  INVOCATION: "单次调用",
  daily: "每日",
  DAILY: "每日",
  monthly: "每月",
  MONTHLY: "每月",
  ask: "询问",
  conversation: "对话",
  coordinator: "协调",
  executor: "执行",
  expert: "专家协作",
  execution: "执行",
  planner: "规划",
  planning: "规划",
  react: "执行判断",
  reflector: "复盘",
  reflection: "复盘",
  researcher: "研究",
  critic: "审查",
  judge_quality: "质量评审",
  judge_safety: "安全评审",
  preference: "偏好",
  constraint: "约束",
  fact: "事实",
  decision: "决定",
  lesson: "经验",
  user: "用户",
  project: "项目",
  always: "始终使用",
  semantic: "按需使用",
  sensitive: "敏感",
  normal: "普通",
  ready: "已就绪",
  failed: "失败",
  pending: "待执行",
  in_progress: "执行中",
  completed: "已完成",
  cancelled: "已取消",
  conversation_domain: "对话",
  plan: "计划",
  research: "研究",
  tool: "工具",
  memory: "记忆",
  quality: "质量",
  cost: "成本",
  latency: "延迟",
  always_include: "始终使用",
  semantic_retrieval: "按需检索",
  normal_sensitivity: "普通",
};

export function localizedCode(value: unknown, fallback = "未知状态"): string {
  const key = String(value ?? "").trim();
  return labels[key] ?? fallback;
}

export function localizedList(values: unknown[], fallback = "无"): string {
  if (!values.length) return fallback;
  return values.map((value) => localizedCode(value, String(value))).join(" · ");
}
